#!/usr/bin/env node
/**
 * Speaks src/remotion/vo-script.json with the best voice this Mac has installed
 * and writes one clip per line, so the composition can place each line on its
 * own beat. Stretching a single long take to fit is what makes narration drift;
 * per-line placement can't drift.
 *
 * Voice quality is entirely down to what's installed. macOS ships only compact
 * voices by default; the Premium/Enhanced ones are a download in System Settings
 * → Accessibility → Spoken Content → System Voice → Manage Voices. This picks the
 * highest quality available and says which one it used, so a robotic result is
 * traceable to a missing download rather than to the script.
 *
 *   npm run voice                 # best available voice
 *   VOICE="Ava (Premium)" npm run voice
 *   RATE=172 npm run voice        # words per minute
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const OUT_DIR = join(ROOT, "assets/remotion/vo");
const SCRIPT = JSON.parse(readFileSync(join(ROOT, "src/remotion/vo-script.json"), "utf8"));
const MANIFEST = join(ROOT, "src/remotion/vo-manifest.json");
const RATE = Number(process.env.RATE ?? 168);
/** Must match DEMO_DURATION / FPS in the composition. */
const FILM_SECONDS = 43;

/** Premium and Enhanced are the neural voices; anything else is the old compact set. */
function pickVoice() {
  if (process.env.VOICE) return process.env.VOICE;
  const listed = execFileSync("say", ["-v", "?"], { encoding: "utf8" })
    .split("\n")
    .map((line) => line.match(/^(.+?)\s{2,}([a-z]{2}_[A-Z]{2})/))
    .filter(Boolean)
    .map(([, name, locale]) => ({ name: name.trim(), locale }))
    .filter((voice) => voice.locale.startsWith("en"));

  const rank = (name) =>
    /\(Premium\)/.test(name) ? 3 : /\(Enhanced\)/.test(name) ? 2 : name === "Samantha" ? 1 : 0;
  const best = listed.sort((a, b) => rank(b.name) - rank(a.name))[0];
  if (!best) throw new Error("no English system voice available");
  return best.name;
}

/** LEI16 keeps it plain PCM, which the bundled ffmpeg can actually decode. */
function speak(text, file) {
  execFileSync("say", [
    "-v", VOICE,
    "-r", String(RATE),
    "--data-format=LEI16@48000",
    "-o", file,
    text,
  ]);
  // 48kHz mono 16-bit: every second is 96,000 bytes, minus the 44-byte header.
  return (statSync(file).size - 44) / 96000;
}

const VOICE = pickVoice();
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const clips = [];
const overruns = [];

SCRIPT.lines.forEach((line, i) => {
  const name = `vo/${String(i + 1).padStart(2, "0")}.wav`;
  const seconds = speak(line.text, join(OUT_DIR, `${String(i + 1).padStart(2, "0")}.wav`));
  const next = SCRIPT.lines[i + 1]?.at ?? FILM_SECONDS;
  const room = next - line.at;
  if (seconds > room) overruns.push({ i: i + 1, seconds, room, text: line.text });
  clips.push({ file: name, at: line.at, seconds: Number(seconds.toFixed(2)) });
  console.log(
    `${String(i + 1).padStart(2, "0")}  ${line.at.toFixed(1).padStart(4)}s  ` +
      `${seconds.toFixed(2)}s / ${room.toFixed(2)}s  ${seconds > room ? "OVERRUN" : "ok"}  ` +
      `${line.text.slice(0, 46)}${line.text.length > 46 ? "…" : ""}`,
  );
});

writeFileSync(
  MANIFEST,
  `${JSON.stringify(
    {
      comment: "Generated by `npm run voice`. Empty clips means the film plays scored, with no narration.",
      voice: VOICE,
      clips,
    },
    null,
    2,
  )}\n`,
);

console.log(`\nvoice   ${VOICE} at ${RATE} wpm`);
console.log(`clips   ${clips.length} → assets/remotion/vo/`);
if (!/\((Premium|Enhanced)\)/.test(VOICE)) {
  console.log(
    "note    this is a compact voice and will sound synthetic. Install a Premium voice in\n" +
      "        System Settings → Accessibility → Spoken Content → Manage Voices, then re-run.",
  );
}
if (overruns.length) {
  console.log(`\n${overruns.length} line(s) run past their beat — raise RATE or shorten the copy:`);
  for (const o of overruns) {
    console.log(`  line ${o.i}: ${o.seconds.toFixed(2)}s in a ${o.room.toFixed(2)}s slot — "${o.text}"`);
  }
  process.exitCode = 1;
}
