/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as RelayRouteImport } from './routes/relay'
import { Route as SoonRouteImport } from './routes/soon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayRoute = RelayRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonRoute = SoonRouteImport.update({
  id: '/soon',
  path: '/soon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/relay': typeof RelayRoute
  '/soon': typeof SoonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/relay': typeof RelayRoute
  '/soon': typeof SoonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/relay': typeof RelayRoute
  '/soon': typeof SoonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/relay' | '/soon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/relay' | '/soon'
  id: '__root__' | '/' | '/app' | '/relay' | '/soon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  RelayRoute: typeof RelayRoute
  SoonRoute: typeof SoonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay': {
      id: '/relay'
      path: '/relay'
      fullPath: '/relay'
      preLoaderRoute: typeof RelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soon': {
      id: '/soon'
      path: '/soon'
      fullPath: '/soon'
      preLoaderRoute: typeof SoonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  RelayRoute: RelayRoute,
  SoonRoute: SoonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
