/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CreateRouteImport } from './routes/create'
import { Route as HomeRouteImport } from './routes/home'
import { Route as RelayRouteImport } from './routes/relay'
import { Route as SoonRouteImport } from './routes/soon'
import { Route as ContextIdRouteImport } from './routes/context.$id'
import { Route as EvalViewerRouteImport } from './routes/eval.viewer'
import { Route as ContextIdIndexRouteImport } from './routes/context.$id.index'
import { Route as ContextIdAskRouteImport } from './routes/context.$id.ask'
import { Route as ContextIdLiveRouteImport } from './routes/context.$id.live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayRoute = RelayRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonRoute = SoonRouteImport.update({
  id: '/soon',
  path: '/soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextIdRoute = ContextIdRouteImport.update({
  id: '/context/$id',
  path: '/context/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalViewerRoute = EvalViewerRouteImport.update({
  id: '/eval/viewer',
  path: '/eval/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextIdIndexRoute = ContextIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContextIdRoute,
} as any)
const ContextIdAskRoute = ContextIdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ContextIdRoute,
} as any)
const ContextIdLiveRoute = ContextIdLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ContextIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/create': typeof CreateRoute
  '/home': typeof HomeRoute
  '/relay': typeof RelayRoute
  '/soon': typeof SoonRoute
  '/context/$id': typeof ContextIdRouteWithChildren
  '/eval/viewer': typeof EvalViewerRoute
  '/context/$id/ask': typeof ContextIdAskRoute
  '/context/$id/live': typeof ContextIdLiveRoute
  '/context/$id/': typeof ContextIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/create': typeof CreateRoute
  '/home': typeof HomeRoute
  '/relay': typeof RelayRoute
  '/soon': typeof SoonRoute
  '/eval/viewer': typeof EvalViewerRoute
  '/context/$id/ask': typeof ContextIdAskRoute
  '/context/$id/live': typeof ContextIdLiveRoute
  '/context/$id': typeof ContextIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/create': typeof CreateRoute
  '/home': typeof HomeRoute
  '/relay': typeof RelayRoute
  '/soon': typeof SoonRoute
  '/context/$id': typeof ContextIdRouteWithChildren
  '/eval/viewer': typeof EvalViewerRoute
  '/context/$id/ask': typeof ContextIdAskRoute
  '/context/$id/live': typeof ContextIdLiveRoute
  '/context/$id/': typeof ContextIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/create'
    | '/home'
    | '/relay'
    | '/soon'
    | '/context/$id'
    | '/eval/viewer'
    | '/context/$id/ask'
    | '/context/$id/live'
    | '/context/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/create'
    | '/home'
    | '/relay'
    | '/soon'
    | '/eval/viewer'
    | '/context/$id/ask'
    | '/context/$id/live'
    | '/context/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/create'
    | '/home'
    | '/relay'
    | '/soon'
    | '/context/$id'
    | '/eval/viewer'
    | '/context/$id/ask'
    | '/context/$id/live'
    | '/context/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CreateRoute: typeof CreateRoute
  HomeRoute: typeof HomeRoute
  RelayRoute: typeof RelayRoute
  SoonRoute: typeof SoonRoute
  ContextIdRoute: typeof ContextIdRouteWithChildren
  EvalViewerRoute: typeof EvalViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay': {
      id: '/relay'
      path: '/relay'
      fullPath: '/relay'
      preLoaderRoute: typeof RelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soon': {
      id: '/soon'
      path: '/soon'
      fullPath: '/soon'
      preLoaderRoute: typeof SoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context/$id': {
      id: '/context/$id'
      path: '/context/$id'
      fullPath: '/context/$id'
      preLoaderRoute: typeof ContextIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval/viewer': {
      id: '/eval/viewer'
      path: '/eval/viewer'
      fullPath: '/eval/viewer'
      preLoaderRoute: typeof EvalViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context/$id/': {
      id: '/context/$id/'
      path: '/'
      fullPath: '/context/$id/'
      preLoaderRoute: typeof ContextIdIndexRouteImport
      parentRoute: typeof ContextIdRoute
    }
    '/context/$id/ask': {
      id: '/context/$id/ask'
      path: '/ask'
      fullPath: '/context/$id/ask'
      preLoaderRoute: typeof ContextIdAskRouteImport
      parentRoute: typeof ContextIdRoute
    }
    '/context/$id/live': {
      id: '/context/$id/live'
      path: '/live'
      fullPath: '/context/$id/live'
      preLoaderRoute: typeof ContextIdLiveRouteImport
      parentRoute: typeof ContextIdRoute
    }
  }
}

interface ContextIdRouteChildren {
  ContextIdAskRoute: typeof ContextIdAskRoute
  ContextIdLiveRoute: typeof ContextIdLiveRoute
  ContextIdIndexRoute: typeof ContextIdIndexRoute
}

const ContextIdRouteChildren: ContextIdRouteChildren = {
  ContextIdAskRoute: ContextIdAskRoute,
  ContextIdLiveRoute: ContextIdLiveRoute,
  ContextIdIndexRoute: ContextIdIndexRoute,
}

const ContextIdRouteWithChildren = ContextIdRoute._addFileChildren(
  ContextIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CreateRoute: CreateRoute,
  HomeRoute: HomeRoute,
  RelayRoute: RelayRoute,
  SoonRoute: SoonRoute,
  ContextIdRoute: ContextIdRouteWithChildren,
  EvalViewerRoute: EvalViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
